export const COINGECKO_API_KEY = process.env.REACT_APP_COINGECKO_API_KEY;
export const COINGECKO_API_URL = process.env.REACT_APP_COINGECKO_API_URL;
export const COINMARKETCAP_API_KEY = process.env.REACT_APP_COINMARKETCAP_API_KEY;
export const COINMARKETCAP_API_URL = process.env.REACT_APP_COINMARKETCAP_API_URL;
export const USED_API = process.env.REACT_APP_USED_API;